version: "3"
services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
  backend:
    build:
      context: backend
    ports:
      - "3001:3001"
    command: python app.py
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    # command: COPY ./db/ /docker-entrypoint-initdb.d/