FROM mysql:latest

COPY ./db/ /docker-entrypoint-initdb.d/

EXPOSE 3306

# FROM mysql:latest
# FROM python:latest

# COPY ./db/ /docker-entrypoint-initdb.d/

# COPY script.sh /app/

# COPY . .

# RUN pip install --upgrade pip

# RUN pip install -r requirements.txt

# RUN chmod +x /app/script.sh

# RUN /app/script.sh

# EXPOSE 3306